In [1]:
from dotenv import load_dotenv
import os
from vnstock import register_user

from vnstock import Vnstock
import pandas as pd

In [2]:
load_dotenv()
api_key = os.getenv("API_KEY")

register_user(api_key=api_key)

✓ API key đã được lưu thành công! (API key saved successfully!)
Bạn đang sử dụng Phiên bản cộng đồng (60 requests/phút)
(You are using Community version - 60 requests/minute)

Để tham gia gói thành viên tài trợ (To join sponsor membership):
  Truy cập: https://vnstocks.com/insiders-program
✓ API key đã được lưu thành công! vnst***73fe
✓ Bạn đang sử dụng Phiên bản cộng đồng (60 requests/phút)

True

In [24]:
stock_universe_vn30 = [
    'ACB', 'BCM', 'BID', 'BVH', 'CTG', 'FPT', 'GAS', 'GVR', 'HDB', 'HPG', 
    'MBB', 'MSN', 'MWG', 'PLX', 'POW', 'SAB', 'SHB', 'SSB', 'SSI', 'STB', 
    'TCB', 'TPB', 'VCB', 'VHM', 'VIB', 'VIC', 'VJC', 'VNM', 'VPB', 'VRE'
]


stock_universe_diamond = [
    'ACB', 'CTG', 'DHC', 'FPT', 'GMD', 'KDH', 'MBB', 'MSB', 'MWG', 'NLG', 
    'OCB', 'PNJ', 'REE', 'TCB', 'TPB', 'VIB', 'VPB', 'VHC'
]

stock_universe_finlead = [
    'ACB', 'BID', 'BVH', 'CTG', 'EIB', 'HDB', 'LPB', 'MBB', 'MSB', 'OCB', 
    'SHB', 'SSB', 'SSI', 'STB', 'TCB', 'TPB', 'VCB', 'VCI', 'VIB', 'VND', 'VPB'
]

stock_universe_custom = [
    'HPG', 'HSG', 'NKG',           # Thép
    'SSI', 'VND', 'VCI', 'HCM',    # Chứng khoán
    'FPT', 'CTR',                  # Công nghệ / Viễn thông
    'DGC', 'DCM', 'DPM',           # Hóa chất / Phân bón
    'PVD', 'PVS', 'BSR',           # Dầu khí
    'KBC', 'SZC', 'IDC', 'VGC',    # BĐS Khu công nghiệp
    'KDH', 'NLG', 'DIG',           # Bất động sản
    'GMD', 'HAH',                  # Cảng biển / Logistics
    'PNJ', 'MWG', 'FRT'            # Bán lẻ
]

In [97]:
from vnstock import Vnstock


def get_data(universe):
    data = {}
    for symbol in universe:
        stock = Vnstock().stock(symbol= symbol , source='KBS')
        df = stock.quote.history(start='2020-01-01', end='2026-04-17')
        data[symbol] = df
    return data


def get_datafield(data):
    data_new = {}
    first_symbol = list(data.keys())[0]
    datafield_list = data[first_symbol].columns

    for datafield in datafield_list:
    # Tạo dict {mã: Series} cho mỗi loại dữ liệu
        datafield_dict = {}
        for symbol, df in data.items():
            datafield_dict[symbol] = df[datafield]

        # Chuyển dict thành DataFrame
        data_new[datafield] = pd.DataFrame(datafield_dict)
    
    return data_new

In [98]:
data = get_data(stock_universe_vn30)

In [107]:
data["BVH"]

                    time   open   high    low  close   volume
0    2020-01-02 07:00:00  58.45  59.21  58.45  58.79    87010
1    2020-01-03 07:00:00  59.13  59.13  58.36  58.45    59290
2    2020-01-06 07:00:00  58.19  58.36  57.59  57.59   129160
3    2020-01-07 07:00:00  57.85  57.94  57.42  57.51    67160
4    2020-01-08 07:00:00  57.00  57.00  55.98  56.23   163230
...                  ...    ...    ...    ...    ...      ...
1564 2026-04-13 07:00:00  77.30  77.30  75.10  75.10   540800
1565 2026-04-14 07:00:00  75.60  77.10  75.10  75.20   389400
1566 2026-04-15 07:00:00  76.00  76.40  73.90  74.00   582300
1567 2026-04-16 07:00:00  73.50  74.30  70.90  73.50  1682500
1568 2026-04-17 07:00:00  73.90  74.10  72.40  72.60   425400

[1569 rows x 6 columns]

In [103]:
get_datafieldd = get_datafield(data)

In [105]:
get_datafieldd["close"]

,ACB,BCM,BID,BVH,CTG,FPT,GAS,GVR,HDB,HPG,...,TCB,TPB,VCB,VHM,VIB,VIC,VJC,VNM,VPB,VRE
0,6.64,27.27,26.46,58.79,9.85,21.18,58.72,9.92,5.51,8.27,...,11.24,6.04,39.24,62.60,4.11,51.10,148.0,72.21,6.70,34.35
1,6.64,26.99,26.35,58.45,9.76,20.82,58.84,10.27,5.46,8.32,...,11.17,6.10,38.85,62.82,4.09,51.24,148.0,72.45,6.65,34.60
2,6.50,26.71,25.84,57.59,9.78,20.61,60.70,10.09,5.35,8.27,...,10.89,6.00,37.81,61.49,4.02,50.88,146.0,71.90,6.50,33.65
3,6.50,25.98,26.35,57.51,9.94,21.00,60.27,9.83,5.29,8.17,...,10.96,6.01,37.94,61.79,4.02,50.97,145.9,72.57,6.63,33.95
4,6.38,25.79,26.57,56.23,9.91,20.54,60.21,9.48,5.29,8.08,...,10.75,5.93,37.60,60.83,3.95,50.79,144.8,72.76,6.55,32.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1564,NaN,NaN,40.35,75.10,34.80,76.00,80.70,NaN,25.90,27.80,...,31.90,16.35,59.20,122.90,NaN,160.00,166.8,62.80,26.90,27.55
1565,NaN,NaN,40.40,75.20,34.90,76.20,79.30,NaN,26.10,28.55,...,32.05,16.45,59.30,128.90,NaN,165.50,166.8,62.00,27.35,27.90
1566,NaN,NaN,40.30,74.00,35.05,75.10,79.20,NaN,26.35,28.05,...,31.85,16.40,59.90,137.00,NaN,177.00,178.2,61.30,27.35,29.30
1567,NaN,NaN,40.20,73.50,34.60,74.10,78.40,NaN,26.10,27.95,...,31.90,16.25,59.40,143.10,NaN,189.30,178.2,61.10,27.60,29.60
1568,NaN,NaN,40.30,72.60,34.85,76.00,80.10,NaN,26.20,28.00,...,32.25,16.25,59.50,135.70,NaN,187.90,177.8,61.30,28.25,28.60

In [11]:
from vnstock import Vnstock
import pandas as pd

stock = Vnstock().stock(symbol='VCI', source='KBS')
df = stock.quote.history(start='2018-01-01', end='2026-04-23')
trading_days = pd.DatetimeIndex(df.index)  # đây là VN trading calendar

# T+2: offset 2 ngày giao dịch thực tế
def add_trading_days(date, n, trading_days):
    idx = trading_days.searchsorted(date)
    return trading_days[idx + n]

In [4]:
import datetime
trading_days

DatetimeIndex([          '1970-01-01 00:00:00',
               '1970-01-01 00:00:00.000000001',
               '1970-01-01 00:00:00.000000002',
               '1970-01-01 00:00:00.000000003',
               '1970-01-01 00:00:00.000000004',
               '1970-01-01 00:00:00.000000005',
               '1970-01-01 00:00:00.000000006',
               '1970-01-01 00:00:00.000000007',
               '1970-01-01 00:00:00.000000008',
               '1970-01-01 00:00:00.000000009',
               ...
               '1970-01-01 00:00:00.000001987',
               '1970-01-01 00:00:00.000001988',
               '1970-01-01 00:00:00.000001989',
               '1970-01-01 00:00:00.000001990',
               '1970-01-01 00:00:00.000001991',
               '1970-01-01 00:00:00.000001992',
               '1970-01-01 00:00:00.000001993',
               '1970-01-01 00:00:00.000001994',
               '1970-01-01 00:00:00.000001995',
               '1970-01-01 00:00:00.000001996'],
              dtype='datetime64[ns]', length=1997, freq=None)

In [12]:
df = df.set_index('time')
trading_days = df.index

In [14]:
trading_days

DatetimeIndex(['2018-01-02 07:00:00', '2018-01-03 07:00:00',
               '2018-01-04 07:00:00', '2018-01-05 07:00:00',
               '2018-01-08 07:00:00', '2018-01-09 07:00:00',
               '2018-01-10 07:00:00', '2018-01-11 07:00:00',
               '2018-01-12 07:00:00', '2018-01-15 07:00:00',
               ...
               '2026-04-10 07:00:00', '2026-04-13 07:00:00',
               '2026-04-14 07:00:00', '2026-04-15 07:00:00',
               '2026-04-16 07:00:00', '2026-04-17 07:00:00',
               '2026-04-20 07:00:00', '2026-04-21 07:00:00',
               '2026-04-22 07:00:00', '2026-04-22 07:00:00'],
              dtype='datetime64[ns]', name='time', length=2071, freq=None)